repos:
  - repo: https://github.com/psf/black
    rev: 22.12.0  # must match requirements-dev.txt
    hooks:
      - id: black
        language_version: python3.9
  - repo: https://github.com/pycqa/isort
    rev: 5.11.4  # must match requirements-dev.txt
    hooks:
      - id: isort
        name: isort (python)

ci:
    autofix_commit_msg: '[pre-commit.ci] auto fixes from pre-commit.com hooks'
    autofix_prs: true
    autoupdate_commit_msg: '[pre-commit.ci] pre-commit autoupdate'
    autoupdate_schedule: weekly
    skip: []
    submodules: false
