repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0  # must match pyproject.toml
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-toml
      - id: check-merge-conflict
      - id: mixed-line-ending
  - repo: https://github.com/psf/black
    rev: 23.1.0 # must match pyproject.toml
    hooks:
      - id: black
        language_version: python3.7
  - repo: https://github.com/pycqa/isort
    rev: 5.12.0 # must match pyproject.toml
    hooks:
      - id: isort
        name: isort (python)

ci:
  autofix_commit_msg: "[pre-commit.ci] auto fixes from pre-commit.com hooks"
  autofix_prs: true
  autoupdate_commit_msg: "[pre-commit.ci] pre-commit autoupdate"
  autoupdate_schedule: quarterly
  submodules: false
