__all__: list[str]  # Y035 "__all__" in a stub file should be identical to "__all__" at runtime
__all__: list[str] = ["foo", "bar", "baz"]
__all__ = ["foo", "bar", "baz"]

foo: int = ...
bar: str = ...
baz: list[set[bytes]] = ...
