__all__: list[str]  # Y035 "__all__" in a stub file must have a value, as it has the same semantics as "__all__" at runtime.
__all__: list[str] = ["foo", "bar", "baz"]
__all__ = ["foo", "bar", "baz"]

foo: int = ...
bar: str = ...
baz: list[set[bytes]] = ...
