class Bad:
    def __repr__(self) -> str:  # Y029 Defining __repr__ or __str__ in a stub is almost always redundant
        ...

    def __str__(self) -> str:  # Y029 Defining __repr__ or __str__ in a stub is almost always redundant
        ...
