import typing
import typing as t
from typing import override, override as over

import typing_extensions

class Foo:
    def f(self) -> None: ...
    def g(self) -> None: ...
    def h(self) -> None: ...
    def j(self) -> None: ...
    def k(self) -> None: ...

class Bar(Foo):
    @override  # Y068 Do not use "@override" in stub files.
    def f(self) -> None: ...
    @typing.override  # Y068 Do not use "@override" in stub files.
    def g(self) -> None: ...
    @t.override  # Ideally we'd catch this too, but the infrastructure is not in place.
    def h(self) -> None: ...
    @over  # Ideally we'd catch this too, but the infrastructure is not in place.
    def j(self) -> None: ...
    @typing_extensions.override  # Y068 Do not use "@override" in stub files.
    def k(self) -> None: ...
