from typing import Any, Callable, ParamSpec, TypeVar

_P = ParamSpec("_P")
_T = TypeVar("_T")
_R = TypeVar("_R")

# GOOD FUNCTIONS
def func() -> None: ...
def func1(arg: int) -> str: ...
def func2(arg: Callable[[int], str]) -> Callable[[str], int]: ...
def func3(arg: Callable[..., str]) -> Callable[[str], str]: ...
def func4(arg: Callable[[str], str]) -> Callable[..., str]: ...
def func5(arg: Callable[[str], _R]) -> Callable[[str], _R]: ...
def func6(arg: Callable[[_T], str]) -> Callable[[_T], int]: ...
def func7(arg: Callable[_P, _R]) -> Callable[_P, _R]: ...
def func8(func: Callable[..., _R], *args: str, **kwargs: int) -> _R: ...
def func9(func: Callable[..., _R], *args: Any, **kwargs: int) -> _R: ...
def func10(func: Callable[..., _R], *args: str, **kwargs: Any) -> _R: ...
def func11(func: Callable[_P, _R], *args: _P.args, **kwargs: _P.kwargs) -> _R: ...
def func12(func: Callable[_P, str], *args: _P.args, **kwargs: _P.kwargs) -> int: ...

# BAD FUNCTIONS
def func13(arg: Callable[..., int]) -> Callable[..., str]: ...  # Y032 Consider using ParamSpec to annotate function "func13"
def func14(arg: Callable[..., _R]) -> Callable[..., _R]: ...  # Y032 Consider using ParamSpec to annotate function "func14"
def func15(arg: Callable[..., _R], *args: Any, **kwargs: Any) -> _R: ...  # Y032 Consider using ParamSpec to annotate function "func15"
def func16(arg: Callable[..., str], *args: Any, **kwargs: Any) -> int: ...  # Y032 Consider using ParamSpec to annotate function "func16"

class Foo:
    def __call__(self, func: Callable[..., _R], *args: Any, **kwargs: Any) -> _R: ...  # Y032 Consider using ParamSpec to annotate function "Foo.__call__"
