from typing import Protocol

class P(Protocol):
    def method1(self, arg: int) -> None: ...  # Y067 Argument "arg" to protocol method "method1" should probably not be positional-or-keyword. Make it positional-only, since usually you don't want to mandate a specific argument name
    def method2(self, arg: str, /) -> None: ...
    def method3(self, *, arg: str) -> None: ...
    def method4(self, arg: int, /) -> None: ...
    def method5(self, arg: int, /, *, foo: str) -> None: ...
    def method6(self, arg, /, *, foo: str) -> None: ...
