import sys

if sys.version_info[0] == 2:
    ...

if sys.version_info[0] == (2, 7):  # Y003
    ...

if sys.version_info[0] == '2':  # Y003
    ...

if sys.version_info[1:] >= (7, 11):  # Y003
    ...

if sys.version_info[::-1] < (11, 7):  # Y003
    ...

if sys.version_info[:3] >= (2, 7):  # Y003
    ...

if sys.version_info[:1] == (2,):
    ...

if sys.version_info[:1] == (2, 7):  # Y005
    ...

if sys.version_info[:2] == (2, 7):
    ...

if sys.version_info[:2] == (2,):  # Y005
    ...

if sys.version_info[:, :] >= (2, 7):  # Y003
    ...

if sys.version_info < [3, 0]:  # Y003
    ...

if sys.version_info < ('3', '0'):  # Y003
    ...

if sys.version_info >= (3, 4, 3):  # Y004
    ...

if sys.version_info == (3, 4):  # Y006
    ...

if sys.version_info > (3, 0):  # Y006
    ...

if sys.version_info <= (3, 0):  # Y006
    ...

if sys.version_info < (3, 5):
    ...

if sys.version_info >= (3, 5):
    ...

if (2, 7) <= sys.version_info < (3, 5):  # Y002
    ...
